# docker run -it --mount type=bind,source="$(pwd)",target=/go/src/github.com/jarl-tornroos/cloudfrontbeat -w /go/src/github.com/jarl-tornroos/cloudfrontbeat golang:1.10 bash

go get github.com/aws/aws-sdk-go/...
go get github.com/oschwald/geoip2-golang/...
make
